config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'work', to: 'pages#work'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render :home
  end

  def about
    render :about
  end

  def work
    render :work
  end

  def contact
    render :contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to My Rails Application</h1>
<p>This is the content of the about page, accessible at '/about'.</p>
<p>There is nothing important about me, but if people want to know, I AM VERY LAZYYYY</p>
<p>
  <%= link_to 'Back To Home', home_path %>
</p>

app/views/pages/contact.html.erb
<h1>Welcome to My Rails Application</h1>
<p>This is the content of the contact page, accessible at '/contact'.</p>
<p>Which you can contact me at 123-456-7890</p>
<p>
  Or you can also go to
  <%= link_to 'FaceBowl',
    'https://www.facebowl.cn/',
    target: '_blank' %>
</p>
<p>
  <%= link_to 'Back To Home', home_path %>
</p>

app/views/pages/home.html.erb
<body>
    <header>
        <h1>Welcome to My Portfolio</h1>
    </header>

    <main>
        <section id="home">
            <h2>Home</h2>
            <p>Welcome to my portfolio website. I am a passionate web developer with expertise in messing around and not doing my
                homework.
            </p>
        </section>

        <section id="about">
            <h2>  <%= link_to 'About Me', about_path %></h2>
            <p>Detailed professional biography, education background, skills, and achievements.</p>
        </section>

        <section id="work">
            <h2>  <%= link_to 'About Work', work_path %></h2>
            <p>Portfolio showcasing detailed descriptions and images of previous projects.</p>
        </section>

        <section id="contact">
            <h2>  <%= link_to 'Contact Me', contact_path %></h2>
            <p>Contact details, social media links, or a simple contact form for inquiries.</p>
        </section>
    </main>

    <footer>
        <p>&copy; 2024 Some very cool awesome name.</p>
    </footer>
</body>
</html>

app/views/pages/work.html.erb
<h1>Welcome to My Rails Application</h1>
<p>This is the content of the work page, accessible at '/work'.</p>
<p>This is the content of the work page, with maybe some images showing I know how to use rail</p>
<%= image_tag 'gangyupic.jpg', class: 'w-100', style: 'max-width: 32rem;' %>
<p>
  <%= link_to 'Back To Home', home_path %>
</p>